//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumWebDriver.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomizationLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomizationLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumWebDriver.Locators.CustomizationLocators", typeof(CustomizationLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;contentContainer&apos;]//img[contains(@src, &apos;/Sunshine/IT_en-us/AcceptAndContinueButton.gif&apos;)].
        /// </summary>
        internal static string acceptCustomizationPreviewBtn_XPath {
            get {
                return ResourceManager.GetString("acceptCustomizationPreviewBtn_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//div[@id=&apos;studio_inlinepreview_jpeg&apos;]/img.
        /// </summary>
        internal static string inlinePreview_XPath {
            get {
                return ResourceManager.GetString("inlinePreview_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;studio_navigation_button_next&apos;].
        /// </summary>
        internal static string nextBtn_XPath {
            get {
                return ResourceManager.GetString("nextBtn_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;txtReference&apos;].
        /// </summary>
        internal static string refField_XPath {
            get {
                return ResourceManager.GetString("refField_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;LowerButtons&apos;]//a[@id=&apos;btnSave&apos;].
        /// </summary>
        internal static string saveOrderDetailsBtn_XPath {
            get {
                return ResourceManager.GetString("saveOrderDetailsBtn_XPath", resourceCulture);
            }
        }
    }
}
