//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumWebDriver.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchPageLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchPageLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumWebDriver.Locators.SearchPageLocators", typeof(SearchPageLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .results-loading-spinner.
        /// </summary>
        public static string centredSpinner_CSS {
            get {
                return ResourceManager.GetString("centredSpinner_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;searchResultsTotalFound&apos;].
        /// </summary>
        public static string matches_XPath {
            get {
                return ResourceManager.GetString("matches_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;searchFilterContainer&apos;].
        /// </summary>
        public static string refineSearchPanel_XPath {
            get {
                return ResourceManager.GetString("refineSearchPanel_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchbutton.
        /// </summary>
        public static string searchBtn_ID {
            get {
                return ResourceManager.GetString("searchBtn_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchterm.
        /// </summary>
        public static string searchField_ID {
            get {
                return ResourceManager.GetString("searchField_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;resultsBarContainer&apos;].
        /// </summary>
        public static string sortingPanel_XPath {
            get {
                return ResourceManager.GetString("sortingPanel_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;startOver&apos;].
        /// </summary>
        public static string startOverLink_XPath {
            get {
                return ResourceManager.GetString("startOverLink_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;a5dd15d0-9d46-4a41-a603-a706013fb23e&apos;]//div[@class=&apos;tacticAction tactic-action-btn&apos;]/a[@href=&apos;/msc/Customize/Index/a5dd15d0-9d46-4a41-a603-a706013fb23e&apos;].
        /// </summary>
        public static string testCustomizableBtn_XPath {
            get {
                return ResourceManager.GetString("testCustomizableBtn_XPath", resourceCulture);
            }
        }
    }
}
